Let's start with a 2d numpy array:

In [28]:
import numpy as np

In [29]:
a = np.arange(0,18).reshape(6,3)*8

In [30]:
a 

array([[  0,   8,  16],
       [ 24,  32,  40],
       [ 48,  56,  64],
       [ 72,  80,  88],
       [ 96, 104, 112],
       [120, 128, 136]])

This can be thought of as an x and y coordinate system:

<img src="https://raw.githubusercontent.com/madesai22/ocean-motion-2021/main/images/IMG_0013.jpg " alt="alt text" width=300 height=300>


Thinking about it in this way, we can access different elements of the array with indicies. For example, 80 is at the point 3,1 (as marked above):

In [46]:
a[3,1]
# try some here as well:


80

If we wanted to print out every element in this numpy array, we might start with the first row a[0,:] and go through it item by item:

In [42]:
a[0,:]

array([ 0,  8, 16])

In [45]:
print(a[0,0])
print(a[0,1])
print(a[0,2])

0
8
16


To go through the whole array, we would then go to the next row, a[1,:]. This would get tedius for a bigger array. Instead, we can use loops. Let's look at a loop that will print all of the rows. Next to the row, I am also printing the value for i when the loop is executed. You can see that each time the loop is executed, i increases and is being used to **index** the array:

In [48]:
for i in range(0,6):
    print(a[i,:], i)

[ 0  8 16] 0
[24 32 40] 1
[48 56 64] 2
[72 80 88] 3
[ 96 104 112] 4
[120 128 136] 5


To get the elements from within each row, we need an additional loop to index the column for each row: 

In [52]:
for i in range(0,6):
    for j in range(0,3):
        print(a[i,j],i,j)

0 0 0
8 0 1
16 0 2
24 1 0
32 1 1
40 1 2
48 2 0
56 2 1
64 2 2
72 3 0
80 3 1
88 3 2
96 4 0
104 4 1
112 4 2
120 5 0
128 5 1
136 5 2


You can cross reference this with our image of our grid: <img src="https://raw.githubusercontent.com/madesai22/ocean-motion-2021/main/images/IMG_0013.jpg " alt="alt text" width=300 height=300>